# Site settings
title: Oscillating Brane Dark Matter Theory
subtitle: The Universe as a Vibrating Membrane
description: >-
  A revolutionary cosmological theory where the universe is a vibrating 4D membrane 
  in 5D space. Dark matter oscillations create dark energy, resolve the S₈ tension, 
  and naturally produce MOND-like effects. Testable predictions for Euclid and PTA.
baseurl: ""
url: "https://higgs-cosmology.com"
author: Romain Provencal

# Build settings
theme: jekyll-theme-minimal
markdown: kramdown
highlighter: rouge

# Math support
kramdown:
  math_engine: mathjax

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation
navigation:
  - title: Home
    url: /
  - title: Theory
    url: /theory/
  - title: Complete Theory
    url: /theory-complete/
  - title: Chronology
    url: /chronology/
  - title: Predictions
    url: /predictions/
  - title: Tools
    url: /tools/
  - title: About
    url: /about/

# Social
github_username: Teleadmin-ai
twitter_username: 

# Analytics (optional)
google_analytics: 

# Exclude from build
exclude:
  - scripts/
  - data/
  - notebooks/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - "*.py"
  - "*.npz"
  - "*.py"
  - "*.npz"