name: CI

on:
  push:
    branches: [ main, restore-working-version ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run brane dynamics simulation
      run: |
        python scripts/brane_dynamics.py
    
    - name: Run 1D oscillation prototype
      run: |
        mkdir -p plots
        python scripts/brane_oscillation_1d.py
    
    - name: Upload plots
      uses: actions/upload-artifact@v3
      with:
        name: simulation-plots
        path: plots/*.png
    
    - name: Check for syntax errors
      run: |
        python -m py_compile scripts/*.py

  build-site:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    
    - name: Build Jekyll site
      run: |
        bundle install
        bundle exec jekyll build
    
    - name: Upload site artifact
      uses: actions/upload-artifact@v3
      with:
        name: jekyll-site
        path: _site/

  generate-pdf:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pypandoc pyyaml
        
    - name: Install pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-plain-generic
    
    - name: Generate PDF
      run: |
        python scripts/generate_pdf.py
    
    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: theory-pdf
        path: output/*.pdf